apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-prs
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - pullRequest:
        github:
          owner: jops8
          repo: argocd-pr-env
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'nginx-{{ .branch_slug }}'
    spec:
      destination:
        namespace: 'ephemeral-{{ .branch_slug }}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: k8s/overlays/r-environment
        repoURL: https://github.com/jops8/argocd-pr-env.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
