apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-prs
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: jops8
          repo: argocd-pr-env
        requeueAfterSeconds: 30
  template:
    metadata:
      name: nginx-{{ branch | replace "/" "-" }}
    spec:
      destination:
        namespace: preview-{{ branch | replace "/" "-" }}
        server: https://kubernetes.default.svc
      project: default
      source:
        path: k8s/overlays/r-environment
        repoURL: https://github.com/jops8/argocd-pr-env
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
