apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-prs
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: jops8
          repo: argocd-pr-env
        requeueAfterSeconds: 30
  template:
    metadata:
      name: nginx-{{ .branch | replace "/" "-" }}
    spec:
      project: default
      source:
        repoURL: 'https://github.com/jops8/argocd-pr-env'
        targetRevision: HEAD
        path: k8s/overlays/r-environment
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'preview-{{ .branch }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
