apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>PR Environment</title>
    </head>
    <body>
        <h1>Welcome to the PR environment!</h1>
        <p>This is a static environment for testing purposes.</p>
    </body>
    </html>
